# Generated by Django 3.2.6 on 2021-09-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('translate', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
